export const ADD_CHAPTER = "ADD_CHAPTER";
export const ADD_SUBSECTION = "ADD_SUBSECTION";
export const TOGGLE_CHAPTER_READY = "TOGGLE_CHAPTER_READY";
export const TOGGLE_SUBSECTION_READY = "TOGGLE_SUBSECTION_READY";
