export const TOGGLE_CHAPTER_READY = "TOGGLE_CHAPTER_READY";
export const TOGGLE_SUBSECTION_READY = "TOGGLE_SUBSECTION_READY";

export const FETCH_CHAPTERS_REQUEST = "FETCH_CHAPTERS_REQUEST";
export const FETCH_CHAPTERS_SUCCESS = "FETCH_CHAPTERS_SUCCESS";
export const FETCH_CHAPTERS_FAILURE = "FETCH_CHAPTERS_FAILURE";

export const ADD_CHAPTER_REQUEST = "ADD_CHAPTER_REQUEST";
export const ADD_CHAPTER_SUCCESS = "ADD_CHAPTER_SUCCESS";
export const ADD_CHAPTER_FAILURE = "ADD_CHAPTER_FAILURE";

export const DELETE_CHAPTER_REQUEST = "DELETE_CHAPTER_REQUEST";
export const DELETE_CHAPTER_SUCCESS = "DELETE_CHAPTER_SUCCESS";
export const DELETE_CHAPTER_FAILURE = "DELETE_CHAPTER_FAILURE";

export const ADD_SUBSECTION_REQUEST = "ADD_SUBSECTION_REQUEST";
export const ADD_SUBSECTION_SUCCESS = "ADD_SUBSECTION_SUCCESS";
export const ADD_SUBSECTION_FAILURE = "ADD_SUBSECTION_FAILURE";

export const DELETE_SUBSECTION_REQUEST = "DELETE_SUBSECTION_REQUEST";
export const DELETE_SUBSECTION_SUCCESS = "DELETE_SUBSECTION_SUCCESS";
export const DELETE_SUBSECTION_FAILURE = "DELETE_SUBSECTION_FAILURE";